### ISSUE TITLE
GB-NHS org link

### ISSUE THREAD

**Issue by michaelwood** [kanedata/find-that-charity#108]
The link for NHS org site has changed and is no longer working: 

```diff
-https://odsportal.hscic.gov.uk/Organisation/Details/{}`
+`https://odsportal.digital.nhs.uk/Organisation/OrganisationDetails?organisationId={}
```
However... of course it's not that simple as the new link no longer allows the 'E' in the org code (i.e. E12345 vs 12345). I couldn't see an obvious place to to a quick .replace("E","") other than in a conditional in `get_links` in organisation.py which wouldn't be very neat..

**Comment by drkane** [comment]
Thanks - that's frustrating. I think it might be worse than that, it looks like while you can search based on the code we have, the record is looked up using a different ID - so a search for [Y00364](https://findthatcharity.uk/orgid/GB-NHS-Y00364) gives an organisationId of [65354](https://odsportal.digital.nhs.uk/Organisation/OrganisationDetails?organisationId=65354&showOpenChildredOnly=True).

I might need to remove the link, or possibly just link to the search page. I'll also have a look at the source data to see if that other organisationId is available in there.
