### ISSUE TITLE
Update recommendations for organisations with GB-MPR identifiers

### ISSUE THREAD

**Issue by KDuerden** [kanedata/find-that-charity#149]
The mutual public register is now the better source for information about registered societies and mutuals, than Companies House. Find that Charity should recommend the GB-MPR above GB-COH when an organisation appears on both lists.

**Comment by drkane** [comment]
Example of this: https://findthatcharity.uk/orgid/GB-MPR-129CUS

**Comment by drkane** [comment]
Fixed through 6ee0d0883d830a9a8d12527c1f2479fa9b39eb5a

**Comment by drkane** [comment]
This is now implemented.

Interestingly the example I gave ([`GB-MPR-129CUS`](https://findthatcharity.uk/orgid/GB-MPR-129CUS)) is actually matched to two different records on Companies House - [`GB-COH-RS00129S`](https://findthatcharity.uk/orgid/GB-COH-RS00129S) and [`GB-COH-IP000129`](https://findthatcharity.uk/orgid/GB-COH-IP000129)

**Comment by KDuerden** [comment]
Oh, that's not great. Hopefully it isn't common. Even more reason to prefer GB-MPR now.
